language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
script: nosetests
install:
  - "pip install -r reqs.pip --use-mirrors"
notifications:
  email:
    - iv.grebenschikov@gmail.com
